spring:
  datasource:
#todo sample and make this file ignored by default
    url: jdbc:h2:../h2/test
    #url=jdbc:h2:mem:mydb #inmemory
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://postgres:5432/dbname
    username: dbuser
    password: 12345678
    driverClassName: org.postgresql.Driver
    platform: postgresql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    platform: postgresql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

# FLYWAY (FlywayProperties)
flyway:
  baseline-on-migrate: true
  locations: classpath:initscripts # locations of migrations scripts
  check-location: true # Check that migration scripts location exists.